version: 2

models:
  - name: dim_airport
    description: "A starter dbt model"
    columns:
      - name: airport_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null



models:
  - name: dim_aircraft
    description: "A starter dbt model"
    columns:
      - name: aircraft_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null          